server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: student
          uri: http://localhost:8081
          predicates:
            - Path=/students/** 
        - id: myClassManagement
          uri: http://localhost:8082
          predicates:
            - Path=/myClasses/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: student
          uri: http://student:8080
          predicates:
            - Path=/students/** 
        - id: myclassmanagement
          uri: http://myclassmanagement:8080
          predicates:
            - Path=/myClasses/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
  
